name: "_Bs4_Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    environment: template_scraper

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd modules/_scraper_template
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run Scraper Script
      env:
        SCRAPE_URL: ${{ vars.SCRAPE_URL }}
      run: |
        source modules/_scraper_template/env/bin/activate
        python modules/_scraper_template/scraper.py

  test-supabase-upload:
    runs-on: ubuntu-latest
    environment: template_scraper

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd modules/_scraper_template
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Test Supabase Upload
      env:
        SUPABASE_URL: ${{ secrets.supabaseUrl }}
        SUPABASE_KEY: ${{ secrets.supabaseKey }}
        BUCKET_NAME: ${{ secrets.bucketName }}
      run: |
        source modules/_scraper_template/env/bin/activate
        python modules/_scraper_template/supabase/upload_image.py
